-- drop table if exists book;
-- drop table if exists author;

create table if not exists author
(
    id      int generated by default as identity primary key,
    name    text not null unique CHECK (NOT name = ''),
    born    timestamptz,
    created timestamptz default current_timestamp,
    updated timestamptz default current_timestamp
);

create table if not exists book
(
    id        int generated by default as identity primary key,
    author_id int  not null references author (id),
    title     text not null,
    genre     text,
    created   timestamptz default current_timestamp,
    updated   timestamptz default current_timestamp
);
